### ISSUE TITLE
There was an error during the cloning process

### ISSUE THREAD

**Issue by andr3i1010** [TooTallNate/nx.js#32]
full error:

```
There was an error during the cloning process:
DegitError: could not find commit hash for v0.0.17
    at Degit._cloneWithTar (C:\Users\andrei1010\AppData\Local\npm-cache\_npx\f598e7a88fe11b20\node_modules\degit\dist\index-688c5d50.js:14258:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Degit.clone (C:\Users\andrei1010\AppData\Local\npm-cache\_npx\f598e7a88fe11b20\node_modules\degit\dist\index-688c5d50.js:14096:4) {
  code: 'MISSING_REF',
  ref: 'v0.0.17'
}
x  Canceled
npm ERR! code 1
npm ERR! path C:\Users\andrei1010
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c create-nxjs-app

npm ERR! A complete log of this run can be found in: C:\Users\andrei1010\AppData\Local\npm-cache\_logs\2023-09-28T14_25_55_116Z-debug-0.log
```

log file:

[2023-09-28T14_25_55_116Z-debug-0.log](https://github.com/TooTallNate/nx.js/files/12750669/2023-09-28T14_25_55_116Z-debug-0.log)

**Comment by TooTallNate** [comment]
Hmmm… is it possible that `git` is not available in your environment? If not, try installing from here: https://git-scm.com/downloads
